@host = http://localhost:3000

### Listar todas as tarefas
GET {{host}}/tasks?limit=10&offset=0
Authorization: 123456

### Buscar tarefa
GET {{host}}/tasks/1

### Deleta tarefa
DELETE  {{host}}/tasks/2

### Criar Tarefa
POST {{host}}/tasks
Content-Type: application/json

{
    "name": "Sujeito",
    "description": "Aprendendo nestJS do zero",
    "userId": 2
}

### Atualizar Tarefa
PATCH  {{host}}/tasks/1
Content-Type: application/json

{
    "name": "Tarefa alterada",
    "completed": true
}

### Buscar usuário
GET {{host}}/users/2

### Cria Usuário
POST   {{host}}/users
Content-Type: application/json

{
    "name": "Pablo George",
    "email": "pablogeokar@gmail.com",
    "password": "123456"    
}

### Atualizar Usuário
PATCH  {{host}}/users/1
Content-Type: application/json

{
    "name": "Pablo George Cardoso Campos Borges"    
}

### Deleta Usuário
DELETE   {{host}}/users/1